import { Inter } from 'next/font/google'
import StyledJsxRegistry from './registry'
import GlobalStyle from '../styles/global.styles';
import { Providers } from '@/redux/provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <GlobalStyle/>
      <StyledJsxRegistry>
        <body className={inter.className}>
            <Providers>
              {children}
            </Providers>
          </body>
      </StyledJsxRegistry>
    </html>
  )
}
